version: '3'

services:
  postgresql:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=postgresql
      - POSTGRESQL_PASSWORD=local123
      - POSTGRESQL_DATABASE=prova